language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: lonsty
  password:
    secure: UfiR53/uI76mjtD/lrwusYqm85vm5Ip0otjj4GYlAegpYWx4t6vd/k51aP0JB4PAGxoobYGigDFWApBdsxRbPjjiFMP/7XslOqRPMYp97kZHGx1SkdQTg+ZQSKridrDAGvjmGOKXEnDpiW7OuEgfBdm963DS75f/axYfhuZ2N+Vy3YkAFmtkyc5jTzCM+jC8Sy+N61xYpAs6NB4bRW7LtgNJ+rn/EWZoZji6qLkYMyKonlvlGhLbbg5chL0LFMeueVRX+qlNbY6aJ0ggSYhijNdWzwBoSlh5gaukVaKGXSOQGhrZG6t/TZD6fW/QwYNWLIN9D8BAQ1FEesJ18JrDcNY3wWnUpGZRqgJk/HMoZ2qhbUuljdsR7+1UcNdzIbXlM7TYunC4MceVPPsfwdpPQ/CE1Ph1mo23EU314mv3CrRANH0K3wX3udWUPlc3hLXe8SuA5e08V3KJoRxaYTP60RPS5M2zK5hZaAATdmrb1Y8t+k4h83314rRh93K8JcWBPmqT4yWiIHLiRM4ROk3886xQeR6mi29soy20VJbwzBgicE6Qec8OYtqDaYvsTrrpYEDXxXXPgfRdJ65oIiB6ItJ83dzVk1IcBvmm8dKG6p7XwtqnN5HcWQ31RsV46hmreeDPqyrYHQ5gfoh8M4ynkEE0ZzH35nUTgbHfKfb83nM=
  skip_cleanup: true
  on:
    tags: true
    repo: lonsty/lotecc
    python: 3.8
