language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  username: __token__
  password:
    secure: VZ9MAMpLF5XkE6OQrdx0/gK3587nE9Es2Y56L0okUFsOjStPxATR7xzqnFonwXUlAwTtXDFxegE1sjlj8cxcaBWOQ+pcPhPEW2NDijdqvBvzF+WbhwPTs3Gn1BAKus2jAS02iYf7PsZt854KfbF3vrpZCl7DQLSTjyWWMwJn0Dw89ElpWrHIV5fB4yFBeWY5HBNVNyRojKs+Fkb/s90fOS6EC63g2FIepiCKoYETCx6/MKvxB5YaNDLTSnk37Ki5FHb4Ox9WuHUNWaQ0ZcDB+3yYwdG9lhmNBYa/6/gcxhz6kFX3dj8rgEYYqTlPTDOLtF/Zj04KLsWCuuSIoU9dTKQW5Jk3lt9hB8QMAWy7sDcciBsuDNDma2ktaBvykwFkvOW28m+F/1XAKMK+o2QxpfT1RU67YLXaBx2T9CAlX1jlOJtvxNCdIlFS2BDy5yFmzMWmupHfjxzgotn485NmEmZVGYO/HpSPc346vfTM33ixbOe8PeqIynUFzTswVJmofCuaQ4T5sQgO9uhJlWPhjD3mKoFjRZ1Vd2dGEFjuI5WmquOKeuYfOOmy3rmqcapo/CdA9cKv88PPGLR6+b6uXjLsz+buUoQXbbdVPOXHsgFZxY/6yLB/4QUfecJQn+AdmtEw0Bw9ExSaUUEGm19YkuYVVngA3knAk7mhDLIlawQ=
  skip_cleanup: true
  on:
    tags: true
    repo: lonsty/lotecc
    python: 3.8
