language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: ZH35ct4bSv10iUTKpKnPdi3uwUljP9sMbICtUiVJxOkaH16xnlTS1iEl98IBXXgBb68F++1LC4P625k9XiJJ1Xd8QAfxZiHcNsfu8cX+vCkCaOmRFdmiz5rqpXgd1ssXaiJlciZAIGQGK5UEN3FGFI3qz8Oe+fLjjCjsWTOrvFVUDi7/5jNkE+X0hiZMCk+WJ37jNSrkm594JGSY0WBOiDEPAnWeYnUrg7vhkrUAH/Ylh/bAaUflFjdg5oriIdDK2CaRf/L8T/byHlS0vjQKIgb9LCekR+a/sgY5V4DLGNd3eyb0nk0MfVdJQQ8EU5xrMyrUFDMNmloDC8zDO0JCmC4O6U+tuQX38gbBON5yFU8iCcljTgWrRdR63I/C110ObNTv2/K5qZAArdWfP6pAIkK/d+k6LKWfseEQIW0YAnYzRquZUbFQeSyPUUTj30ikNdmcMAg9FyxsVSXc2gWTMhWeskSrkF1FQjnOsd16aZzbg3ciBTTASG9K/zu+dXdRnM+Ji6le0AIOeSngtACDn1hg8WjlwW2ODKZVN6X2OmL0Tmy5rRHWFILW8LT0tYXbTrxlg8fNZhiQKGPIm98PDbxe0WQMbSdB3ZbE/SLGpz0QY0A+l+2iN9YnO4AfVKML37swtd03TOBJfVFbDwek4Rdmx8i3b9W2HuOMywbPsp8=
  skip_cleanup: true
  on:
    tags: true
    repo: lonsty/lotecc
    python: 3.8
