language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  username: lonsty
  password:
    secure: HsFvgycG6TNMw5d43PkwUNosfj8nytEctcQDoraTZEu+YkiP0FJ07FjN+GEqJYCu3FyPMedAi0Auhrm3Uzvu826jyYqNrRIkZBzgrmc3OMdJF4dcXmrU23y9GFWcOXdTel1K590uBGcqu1xhKw6fjBeIVuHCf8Sh6rWtURYCLlIFxTAx5/EZFCWMva1nqSKPvIkttOT8H5SXFRiEGzFvKtA9LKKx0Hg5S3dyPWB2Xr2xFnDsCD6t+rNC8eY2t22abLCE02LIdOWAfSOXdn1fjGz9xJC+2RGHO58lU3PMSDnbNLGDa7Db1dd16oDW7dTEaArQAm819XrHM6+8n/0ovFWyNrVD4oqqNj2kWeHg0hrzhrOsNQ+3xrhsU3l3x6nh5Ul8MVCRNHv7ce75EZmTW8SWPHHIHZP3FtnraWmIykwvV0LrX+hXdh27sFK996z5BeZkp4DcdxROCAU77lx+wxsIARoxW9J4J/7gGee1YoHUCOqz6gaNBepEg5Jd+cmLL+pb+4C2CTNFXj/bv0V9ndYa3WPq3MYT6maez1LC/PPe9baWTqx1rbjoXKcBDvlTC79KeeE5eRkKvB/Uh3Ffg/1SzZ0x2KvdAaapCqCmobVTVUPvcuKkTdhzBc8Inc+Q9KjZ42eEwbEeCGswToFtVgq5eO3+/1pANbgzcpcx72Y=
  skip_cleanup: true
  on:
    tags: true
    repo: lonsty/lotecc
    python: 3.8
